### ISSUE TITLE
VS 2017 support

### ISSUE THREAD

**Issue by jakubbukaj** [Sebazzz/VsRemovePublishButton#1]
Hello,
could you please add support for VS 2017 in vsixmanifest? 

Thanks for great extension

**Comment by Sebazzz** [comment]
Sorry, my reply via e-mail did not arrive.

Did you try the extension on 2017? If you did, I will surely add it to the manifest. If not, I'd like to wait until 2017 stabilizes because then I will install it myself and test the extension.

**Comment by jakubbukaj** [comment]
Hello,
I have installed VS 2017. It seems that Publish button was changed to "Add to Source control". I am unable to install your extension and try it since there is missing support in vsixmanifest for VS 2017.

I also noticed there is pretty new Won't fix issue posted in visualstudio developer community about hiding this button [here](https://developercommunity.visualstudio.com/content/problem/24554/vs2017-add-to-source-control-in-status-bar-draws-t.html).

Thanks

**Comment by Sebazzz** [comment]
Thanks - I'm on it.

**Comment by Sebazzz** [comment]
[Updated to 1.2](https://marketplace.visualstudio.com/vsgallery/6e8c558f-b681-4a6a-931b-4efb04714364).

**Comment by jakubbukaj** [comment]
Works like a charm! Thanks for simple, but awesome extension!
